version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest 
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3303:3303"
    environment:
      MYSQL_DATABASE: volaAgency
      MYSQL_USER: adminUser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
      image: node:13.7
      container_name: npm
      volumes:
        - ./src:/var/www/html
      working_dir: /var/www/html
      entrypoint: ['npm']

  artisan:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: artisan
      volumes:
        - ./src:/var/www/html
      depends_on:
        - mysql
      working_dir: /var/www/html
      entrypoint: ['/var/www/html/artisan']
      networks:
        - laravel

  prisma:
      image: prismagraphql/prisma:1.34
      container_name: prisma
      restart: always
      ports:
        - "4460:4466"
      environment:
        PRISMA_CONFIG: |
          managementApiSecret: my-server-secret-123
          port: 4460
          databases:
            default:
              connector: mysql
              migrations: true
              host: db
              port: 3303 
              user: root
              password: secret

  phpmyadmin: 
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: phpmyadmin
      depends_on: 
        - mysql
      ports: 
        - "8081:80"
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: secret
      networks: 
        - laravel